# Project information
site_name: biRNN-DVC
# defeine TOC or order of website-
nav:
  - Home: index.md

site_author: Aman Gupta
site_description: >-
  DESCRIPTION

# Repository
repo_name: AmanGupta0112/biRNN-DVC
repo_url: https://github.com/AmanGupta0112/biRNN-DVC

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/AmanGupta0112
    - icon: fontawesome/brands/twitter
      link: ""
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/aman-gupta-58059614b/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/aman_gupta1201/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
  - search

copyright: |
  &copy; 2023 <a href="https://github.com/AmanGupta0112"  target="_blank" rel="noopener">Aman Gupta</a>